<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE email[
    <!ELEMENT email (from*, to*, content*)>
        <!ELEMENT from (#PCDATA)>
        <!ELEMENT to (#PCDATA)>
        <!ELEMENT content (person, course*, exercises+, person)>
        <!ELEMENT person (#PCDATA)>
        <!ELEMENT course (#PCDATA)>
        <!ELEMENT exercises (exercise+)>
        <!ELEMENT exercise ((topic*), (description*))>
        <!ELEMENT topic (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
]>
<email>
    <from> luca.rossi.917@gmail.com </from>
    <to> atzeni@dia.uniroma3.it </to>
    <content>
        <person> Paolo </person>
        <course> webengineering </course>
        <exercises>
            <exercise>
                <topic> DTD </topic>
                <description> From Instance to DTD </description>
            </exercise>
            <exercise>
                <topic> XPath </topic>
                <description> Find students with average grade better than 26</description>
            </exercise>
        </exercises>
        <person> Best Regards,
        Luca </person>
    </content>
</email>